stages:
 - build
 - install

build:
  image: 47.97.82.62:8888/base/node:12.10.0
  stage: build
  script:
    - date
    - npm config set sass_binary_site=https://npm.taobao.org/mirrors/node-sass/
    - npm config set registry=https://registry.npm.taobao.org
    - npm install -g @vue/cli@3.11.0
    - npm install
    - npm run build
    - tar -czvf dist.tar.gz dist/
  tags:
    - java
  artifacts:
    paths:
      - dist.tar.gz

job1:
  image: docker:stable
  stage: install
  dependencies:
    - build
  tags:
    - java
  before_script:
    - docker info
  script:
    - tar -zxvf dist.tar.gz
    - docker build -t 47.97.82.62:8888/web/7kid_classboard:$CI_COMMIT_REF_SLUG .
    - docker login --username=au1 -p Au1password 47.97.82.62:8888
    - docker push 47.97.82.62:8888/web/7kid_classboard:$CI_COMMIT_REF_SLUG
    - docker rmi 47.97.82.62:8888/web/7kid_classboard:$CI_COMMIT_REF_SLUG
